build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Crowdsec Cloudflare Bouncer"
  org.opencontainers.image.description: "Crowdsec bouncer for Cloudflare"
  org.opencontainers.image.source: "https://github.com/krisbogaerts/home-assistant-addons"
  org.opencontainers.image.licenses: "MIT"
