name: "Crowdsec Cloudflare Bouncer"
description: "Crowdsec Cloudflare bouncer"
codenotary: k@bogaerts.org
version: "v0.0.3"
slug: crowdsec-cloudflare-bouncer
init: false
auth_api: true
arch:
  - x64

options:
  api_url: "http://424ccef4-crowdsec:8080/"
  api_key: ""
  update_frequency: "10s"
  log_level: info
  cloudflare_id: ""
  cloudflare_token: ""
  cloudflare_zone_id: ""
schema:
  api_url: str
  api_key: str
  update_frequency: str
  log_level: list(info|error|debug)
  cloudflare_id: str
  cloudflare_token: str
  cloudflare_zone_id: str
map:
  - config:rw
